include:
  - board: nice_nano_k
    shield: cornix_dongle_adapter
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: cornix_dongle_qf

  # - board: nice_nano//zmk
  #   shield: settings_reset
  #   snippet: studio-rpc-usb-uart nrf52840-nosd
  #   artifact-name: nice_reset
    
  - board: cornix_ph_left
    artifact-name: cornix_left_for_dongle
    
  - board: cornix_right
    artifact-name: cornix_right_for_dongle

  - board: cornix_right
    shield: settings_reset
    snippet: studio-rpc-usb-uart nrf52840-nosd
    artifact-name: cornix_reset
  
  # - board: cornix_left
  #   snippet: studio-rpc-usb-uart
  #   cmake-args: -DCONFIG_ZMK_STUDIO=y
  #   artifact-name: cornix_left_default

  # - board: cornix_right
  #   snippet: studio-rpc-usb-uart
  #   cmake-args: -DCONFIG_ZMK_STUDIO=y
  #   artifact-name: cornix_right
