manifest:
  remotes:
    - name: Iemooon
      url-base: https://github.com/Iemooon
  projects:
    - name: zmk-833
      remote: Iemooon
      revision: main
      clone-depth: 1
      import:
        file: app/west.yml
  self:
    path: config
